/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package edu.union;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int block=0x7f020000;
        public static final int glass=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int zeus=0x7f020003;
    }
    public static final class id {
        public static final int text=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int eighth=0x7f040008;
        public static final int eleventh=0x7f04000b;
        public static final int fifth=0x7f040005;
        public static final int first=0x7f040001;
        public static final int fourth=0x7f040004;
        public static final int ninth=0x7f040009;
        public static final int second=0x7f040002;
        public static final int seventh=0x7f040007;
        public static final int sixth=0x7f040006;
        public static final int tenth=0x7f04000a;
        public static final int third=0x7f040003;
    }
}
